source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
ruby '2.6.5'
gem 'amazing_print'
gem 'attr_encrypted', '~> 3.1.0'
gem 'bootsnap', '>= 1.4.2', require: false
gem 'bootstrap4-kaminari-views'
gem 'devise'
gem 'devise-bootstrap-views', '~> 1.0'
gem 'draper'
gem 'faraday'
gem 'faraday_middleware'
gem 'faraday_middleware-aws-sigv4'
gem 'fuzzy_match'
gem 'high_voltage'
gem 'httparty'
gem 'kaminari'
gem 'loaf'
gem 'mechanize'
gem 'money'
gem 'ofx', github: 'annacruz/ofx'
gem 'omniauth'
gem 'omniauth-ynab'
gem 'pg', '>= 0.18', '< 2.0'
gem 'pry-rails'
gem 'puma', '~> 4.3'
gem 'rails', '~> 6.0.0'
gem 'rollbar'
gem 'sass-rails', '~> 5'
gem 'sidekiq'
gem 'sidekiq-cron'
gem 'sidekiq-unique-jobs'
gem 'simple_form'
gem 'turbolinks', '~> 5'
gem 'watir'
gem 'webpacker', '~> 4.0'
group :development do
  gem 'letter_opener'
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'rubocop'
  gem 'rubocop-rails'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'web-console', '>= 3.3.0'
end
group :development, :test do
  gem 'pry-byebug'
  gem 'rspec-rails', '~> 3.8'
  gem 'webdrivers'
end
group :test do
  gem 'factory_bot'
end
gem 'marco-polo'
